# Generated by Django 3.2.8 on 2022-01-22 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='oferta',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='productospedido',
            name='estado',
            field=models.IntegerField(choices=[(3, 'Enviado'), (1, 'Confirmado'), (0, 'Pendiente'), (2, 'Pagado'), (4, 'Recibido')], default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.IntegerField(choices=[(2, 'Comprador'), (0, 'Administrador'), (1, 'Vendedor')]),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='valoracion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
