# Generated by Django 3.2.8 on 2022-01-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20220122_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productospedido',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Confirmado'), (2, 'Pagado'), (4, 'Recibido'), (3, 'Enviado')], default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Administrador'), (2, 'Comprador'), (1, 'Vendedor')]),
        ),
    ]
